apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: object-detection
    serving.kserve.io/deploymentMode: ModelMesh
  labels:
    name: object-detection
    opendatahub.io/dashboard: "true"
  name: object-detection
  namespace: object-detection
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
        version: "1"
      runtime: object-detection
      storage:
        key: aws-connection-s3-creds
        path: model