apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: debug-volume
  name: debug-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem